version: '3'

services:

  kaldi-logmel:
    build: ./kaldi_logmel/
    volumes:
      - tmp-volume:/tmp/
    container_name: kaldi-logmel

  gentle-xmlrpc:
    build: ./gentle_xmlrpc/
    volumes:
      - tmp-volume:/tmp/
    container_name: gentle-xmlrpc

  tensorflow-serving-vad:
    image: tensorflow/serving:latest
    restart: unless-stopped
    volumes:
      - ./tensorflow_serving_vad:/models
    command: --model_config_file=/models/models.cfg
    container_name: tensorflow-serving-vad

  autotimecode-api:
    build: ./autotimecode_api/
    container_name: autotimecode-api
    ports:
      - 5155:5155

volumes:
  tmp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/Beining/Documents/coding/VAD/2005

